# Generated by Django 5.0.6 on 2024-06-11 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_raised', models.DateField()),
                ('description', models.TextField()),
                ('likelihood', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')])),
                ('impact', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')])),
                ('owner', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mitigating_action', models.TextField()),
            ],
        ),
    ]
