# Generated by Django 5.0.6 on 2024-06-10 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Risk_register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk',
            name='date_raised',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='risk',
            name='likelihood',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')]),
        ),
    ]
