# Generated by Django 5.0.6 on 2024-06-10 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Risk_register', '0002_alter_risk_date_raised_alter_risk_likelihood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk',
            name='likelihood',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')]),
        ),
    ]
