# Generated by Django 5.0.6 on 2024-06-11 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Risk_register', '0003_alter_risk_likelihood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk',
            name='impact',
            field=models.IntegerField(choices=[(1, 'low'), (2, 'medium'), (3, 'high')]),
        ),
        migrations.AlterField(
            model_name='risk',
            name='likelihood',
            field=models.IntegerField(choices=[(1, 'low'), (2, 'medium'), (3, 'high')]),
        ),
    ]
